### ISSUE TITLE
Олег Юрьевич не знает английский

### ISSUE THREAD

**Issue by Liconite** [Babchenok1work/PythonTasks#2]
https://github.com/Babchenok1work/PythonTasks/blob/3dcde12865214508221326f3056e418bd8943f9b/FunctionTasks2/Task4.py#L2

cacluate-calculate

**Comment by Babchenok1work** [comment]
Задание 3: Вычисление оптимальных координат цели для ракетной атаки

На карте размером 100×100 расположены объекты военной инфраструктуры. Каждый из объектов имеет целочисленные координаты и ценность (тоже целое число в интервале [0,100]). Информация обо всех военных объектах хранится в текстовом файле в следующем формате:

    Каждая строчка содержит три целых числа, разделённых пробелом:

    x y w

    Здесь x,y - декартовы координаты объекта, число w - ценность объекта.
    В одном файле может быть записано несколько объектов, каждый объект - в новой строке.

Задача Необходимо написать программу для расчёта координат (strike_x, strike_y) нанесения оптимального ракетного удара одной ракетой (приносящего максимальный урон военной инфраструктуре), если известно, что радиус поражения ракеты составляет R. Программа при запуске принимает на вход два аргумента командной строки:

    Путь к файлу, в котором лежат координаты.
    Радиус поражения R.

Выдаёт на экран три числа: x y v

    x - координата x нанесения удара
    y - координата y нанесения удара
    v - суммарная ценность уничтоженных объектов

Например: get_target targets.txt 10

Требования:

    Программа представляет собой модуль, устанавливающийся командой python3 setup.py install.
    Программа должна проверять корректность входных данных.
    Количество целей в файле targets.txt может быть произвольным.

Подсказка: Будут ли координаты нанесения удара целыми числами?
